apiVersion: apps/v1
kind: Deployment
metadata:
  name: codius-web
  namespace: default
  labels:
    app: codius-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codius-web
  template:
    metadata:
      labels:
        app: codius-web
    spec:
      containers:
      - name: codius-web
        image: codius/codius-web
